-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 18:02:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestion-consultas-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion-consultas-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion-consultas-db` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestion-consultas-db` ;

-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`usuario` (
  `legajo` INT NOT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`legajo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_hora_fin` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `modalidad` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `profesor_legajo` INT NULL DEFAULT NULL,
  `cupo` INT NULL DEFAULT NULL,
  `materia_id` INT NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `motivo_bloqueo` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_hora_reprogramada` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`profesor_legajo`)
    REFERENCES `gestion-consultas-db`.`usuario` (`legajo`),
  CONSTRAINT `consulta_ibfk_2`
    FOREIGN KEY (`materia_id`)
    REFERENCES `gestion-consultas-db`.`materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`inscripcion` (
  `nro` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NULL DEFAULT NULL,
  `alumno_id` INT NULL DEFAULT NULL,
  `fecha_inscripcion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_id` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`nro`),
  CONSTRAINT `inscripcion_ibfk_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `gestion-consultas-db`.`consulta` (`id`),
  CONSTRAINT `inscripcion_ibfk_2`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `gestion-consultas-db`.`usuario` (`legajo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestion-consultas-db`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-consultas-db`.`usuario_rol` (
  `usuario_legajo` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`usuario_legajo`, `rol_id`),
  CONSTRAINT `usuario_rol_ibfk_1`
    FOREIGN KEY (`usuario_legajo`)
    REFERENCES `gestion-consultas-db`.`usuario` (`legajo`),
  CONSTRAINT `usuario_rol_ibfk_2`
    FOREIGN KEY (`rol_id`)
    REFERENCES `gestion-consultas-db`.`rol` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO materia (`nombre`) VALUES ("Fisica 2");
INSERT INTO materia (`nombre`) VALUES ("Fisica");
INSERT INTO materia (`nombre`) VALUES ("Analisis Matematico 2");
INSERT INTO materia (`nombre`) VALUES ("Analisis Matematico");
INSERT INTO materia (`nombre`) VALUES ("Analisis de sistemas");
INSERT INTO materia (`nombre`) VALUES ("Diseño de sistemas");
INSERT INTO materia (`nombre`) VALUES ("Administracion de recursos");
INSERT INTO materia (`nombre`) VALUES ("Quimica");
INSERT INTO materia (`nombre`) VALUES ("Algebra y Geometria Analitica");
INSERT INTO materia (`nombre`) VALUES ("Sistemas Operativos");
INSERT INTO materia (`nombre`) VALUES ("Matematica Superior");

INSERT INTO rol(`descripcion`) VALUES ("Admin"), ("Alumno"), ("Profesor");

INSERT INTO usuario (`legajo`, `nombre`, `apellido`, `email`, `password`) VALUES (11111, "Admin", "Admin", "admin@gmail.com", "21232f297a57a5a743894a0e4a801fc3" ); 
INSERT INTO usuario (`legajo`, `nombre`, `apellido`, `email`, `password`) VALUES (11222, "Alumno", "Alumno", "alumno@gmail.com", "c6865cf98b133f1f3de596a4a2894630");
INSERT INTO usuario (`legajo`, `nombre`, `apellido`, `email`, `password`) VALUES (11331, "Profesor", "Profesor", "profesor@gmail.com", "793741d54b00253006453742ad4ed534");
INSERT INTO usuario (`legajo`, `nombre`, `apellido`, `email`, `password`) VALUES (11332, "Profesor2", "Profesor2", "profesor2@gmail.com", "793741d54b00253006453742ad4ed534");

INSERT INTO usuario_rol (`usuario_legajo`, `rol_id`) VALUES (11111, 1), (11222, 2), (11331, 3), (11332, 3);